// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpd2kug35auB8xchIishDqMKNdNUpP6bs',
    appId: '1:630553124921:web:64527364635daf69ceede8',
    messagingSenderId: '630553124921',
    projectId: 'cancerconnector',
    authDomain: 'cancerconnector.firebaseapp.com',
    storageBucket: 'cancerconnector.appspot.com',
    measurementId: 'G-SS53NY7TGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs6kWG1_fDRf5w3wVBkTRuXtOG3_fRxTQ',
    appId: '1:630553124921:android:cef0bb47aa205e86ceede8',
    messagingSenderId: '630553124921',
    projectId: 'cancerconnector',
    storageBucket: 'cancerconnector.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvdpXXORLYOHI05GfxVee6Ch3tdt39wOw',
    appId: '1:630553124921:ios:fa0ec6ab1c501527ceede8',
    messagingSenderId: '630553124921',
    projectId: 'cancerconnector',
    storageBucket: 'cancerconnector.appspot.com',
    iosBundleId: 'com.cancerconnector.cancerconnector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvdpXXORLYOHI05GfxVee6Ch3tdt39wOw',
    appId: '1:630553124921:ios:a5ddc7119433f6e7ceede8',
    messagingSenderId: '630553124921',
    projectId: 'cancerconnector',
    storageBucket: 'cancerconnector.appspot.com',
    iosBundleId: 'com.cancerconnector.cancerconnector.RunnerTests',
  );
}
