// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpOt1V5h9h-pRq1_Ov41KVUqe332wl698',
    appId: '1:111350797979:web:ffd251b368e8c2f381983e',
    messagingSenderId: '111350797979',
    projectId: 'pikideliveryapp',
    authDomain: 'pikideliveryapp.firebaseapp.com',
    storageBucket: 'pikideliveryapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Upcbv7I1FsYILR1VW8ucPMykwSjrpvk',
    appId: '1:111350797979:android:7ceb0b5c2c73712381983e',
    messagingSenderId: '111350797979',
    projectId: 'pikideliveryapp',
    storageBucket: 'pikideliveryapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXPqKQ-NqWSJuxTOTxOXekaU2UU1PiCiU',
    appId: '1:111350797979:ios:bc5246ad9723d03f81983e',
    messagingSenderId: '111350797979',
    projectId: 'pikideliveryapp',
    storageBucket: 'pikideliveryapp.appspot.com',
    iosClientId: '111350797979-qlq2qarnb5n145t98rrkh1apftpldc08.apps.googleusercontent.com',
    iosBundleId: 'com.pikidelivery.pikideliveryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXPqKQ-NqWSJuxTOTxOXekaU2UU1PiCiU',
    appId: '1:111350797979:ios:aa1dad333e98fd5781983e',
    messagingSenderId: '111350797979',
    projectId: 'pikideliveryapp',
    storageBucket: 'pikideliveryapp.appspot.com',
    iosClientId: '111350797979-r0dqqhd90o747nfna8qa1d14dn8ot0gq.apps.googleusercontent.com',
    iosBundleId: 'com.pikidelivery.pikideliveryapp.RunnerTests',
  );
}
